version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mcp
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-here
      - API_V1_STR=/api/v1
      - PROJECT_NAME=MCP
      - BACKEND_CORS_ORIGINS=["*"]
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mcp
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    command: celery -A app.core.celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mcp
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - app
      - db
      - redis

volumes:
  postgres_data:
  redis_data:

networks:
  mcp-network:
    driver: bridge 